const data = [
  {
    id: 1,
    category: "html",
    title: "Design Within Reach",
    description: "HTML & CSS",
    img: "./img/design.png",
    live: "https://design-html.netlify.app/",
    github: "https://github.com/zioan/design",
  },
  {
    id: 2,
    category: "html",
    title: "EdgeLedger",
    description: "HTML & CSS",
    img: "./img/edge.png",
    live: "https://edge-html.netlify.app/#home",
    github: "https://github.com/zioan/EdgeLedger",
  },
  {
    id: 3,
    category: "html",
    title: "HTML Clone",
    description: "HTML & CSS",
    img: "./img/doto.png",
    live: "https://doto-html-clone.netlify.app/",
    original:
      "http://preview.codecanyon.net/item/mega-html5-banners-bundle-140-multi-purpose-banners/full_screen_preview/21213851?_ga=2.43060965.1385975857.1611996225-2138465394.1611996219",
    github: "https://github.com/zioan/doto",
  },
  {
    id: 4,
    category: "html",
    title: "Webpage Clone",
    description: "HTML & CSS",
    img: "./img/clone1.png",
    live: "https://clone1-html.netlify.app/",
    github: "https://github.com/zioan/clone1",
  },
  {
    id: 5,
    category: "javascript",
    title: "Nikola Tesla",
    description: "Javascript JSON fetch",
    img: "./img/tesla.png",
    live: "https://tesla-javascript.netlify.app/",
    github: "https://github.com/zioan/tesla",
  },
  {
    id: 6,
    category: "javascript",
    title: "MovieDB",
    description: "Javascript & MovieDB API",
    img: "./img/movie.png",
    live: "https://movie-javascript.netlify.app/",
    github: "https://github.com/zioan/movie-app",
  },
];

export default data;
