const data = [
  {
    id: 1,
    category: "html",
    title: "Design Within Reach",
    description: "HTML & CSS",
    img: "./img/design.png",
    live: "https://design-html.netlify.app/",
    github: "https://github.com/zioan/design",
  },
  {
    id: 2,
    category: "html",
    title: "EdgeLedger",
    description: "HTML & CSS",
    img: "./img/edge.png",
    live: "https://edge-html.netlify.app/#home",
    github: "https://github.com/zioan/EdgeLedger",
  },
  {
    id: 3,
    category: "html",
    title: "Hotel",
    description: "HTML & CSS",
    img: "./img/hotel.png",
    live: "https://hotel-html.netlify.app/",
    github: "https://github.com/zioan/hotel",
  },
  {
    id: 4,
    category: "html",
    title: "Webpage Clone",
    description: "HTML & CSS",
    img: "./img/clone1.png",
    live: "https://clone1-html.netlify.app/",
    github: "https://github.com/zioan/clone1",
  },
  {
    id: 5,
    category: "javascript",
    title: "Nikola Tesla",
    description: "Javascript JSON fetch",
    img: "./img/tesla.png",
    live: "https://tesla-javascript.netlify.app/",
    github: "https://github.com/zioan/tesla",
  },
  {
    id: 6,
    category: "javascript",
    title: "MovieDB",
    description: "Javascript & MovieDB API",
    img: "./img/movie.png",
    live: "https://movie-javascript.netlify.app/",
    github: "https://github.com/zioan/movie-app",
  },
];

export default data;
